### ISSUE TITLE
Keyboard Submit

### ISSUE THREAD

**Issue by mjmarrazzo** [ajinasokan/autopilot#3]
Testing an app for work, and we have a search bar and there isn't a search button, cause you would typically press enter after the search term. We are using both autopilot to handle all flutter things and appium for handling system dialog and permissions. We could do a workaround with appium, but we're trying to use it as least as possible. 

So I'm looking for a way to send a keyboard submit with autopilot. Have tried adding in various line endings, but nothing seems to work. Still looking into ways to do this, but if you have any input, that would be great.

**Comment by mjmarrazzo** [comment]
```
 void submit() {
    ServicesBinding.instance.defaultBinaryMessenger.handlePlatformMessage(
      SystemChannels.textInput.name,
      SystemChannels.textInput.codec.encodeMethodCall(
        MethodCall('TextInputClient.performAction',
            <dynamic>[_clientId, TextInputAction.done.toString()]),
      ),
      (ByteData data) {},
    );
  }
```

So I did happen to find some stuff for TextInputClient.performAction, and I don't mind submitting a pull request, but was curious on your thoughts on this. There are other [actions](https://api.flutter.dev/flutter/services/TextInputAction-class.html) that others might need. 
Edit: fix code formatting

**Comment by ajinasokan** [comment]
This will be really useful. You can add another method next to [TextInputDriver.type](https://github.com/ajinasokan/autopilot/blob/master/lib/src/text_input.dart#L11) that accepts a string corresponding to the enum value and forward it like in your snippet.

And in the API you can add POST [/keyboard](https://github.com/ajinasokan/autopilot/blob/master/lib/src/driver.dart#L103) for receiving this value from the test script.
