### ISSUE TITLE
GET /drag Doesn't Seem to be Working

### ISSUE THREAD

**Issue by mjmarrazzo** [ajinasokan/autopilot#5]
I have a question about the /drag endpoint, because it doesn't seem to be working for me.
The `x` and `y` params are the starting coordinates, are `dx` and `dy` supposed to be the end coordinates or just the offset on which it should move to? Trying to figure out if I'm giving it the wrong values.

Basically we have a slider that I need to slide to trigger a "check out."
I get the position of the Icon thats on the far left of the slider by calling `/texts?key=$key`. I've tried using a bunch of different things and nothing seems to work and I've tried looking at the _doDrag function and am getting lost inside of it.

**Comment by mjmarrazzo** [comment]
Still been looking into this, but this is the package we're using in case that helps.
https://pub.dev/packages/slider_button

**Comment by ajinasokan** [comment]
@mjmarrazzo It is actually the offset. Can you give an example code with which I can try reproducing this?

**Comment by mjmarrazzo** [comment]
Yeah, I'll try and see if I can get a minimal app with a test file that fails to drag. I'll link to the repo once I get it up.

**Comment by mjmarrazzo** [comment]
Sorry, didn't have much time over the weekend. I just tried to make a sample app to commit to github, but this sample app is currently working with /drag. I'm looking into our app code to see if I can reproduce somehow. Will update if I can find anything reproducible.

**Comment by ajinasokan** [comment]
Cool. I'm guessing it could be due to the positioning of the Widget. Do you have any animations like translation applied on it?

**Comment by mjmarrazzo** [comment]
I forgot to respond earlier and happened to catch your email. So it looks like the /drag endpoint works when I'm running the app through flutter run, but it does not work when you build an apk and install through adb. Any ideas on why that would be? I can post the app source that I'm using if that would help you.

**Comment by mjmarrazzo** [comment]
Sorry, something weird is going on, because now it seems like it is working on the apk build. I was just about to go to sleep, but I'll look into it more first thing in the morning.

**Comment by mjmarrazzo** [comment]
So it now seems to be working for me pretty realiably. Sorry for the false alarm. Closing the issue out.
