### ISSUE TITLE
Flutter 2.0 Compilation Errors

### ISSUE THREAD

**Issue by mjmarrazzo** [ajinasokan/autopilot#6]
https://github.com/ajinasokan/autopilot/blob/93b8db41c739fdc059161b05925d48e4312575f8/lib/src/driver.dart#L208-L218

Any of the code that creates a TestGesture is a compilation error after flutter 2.0. It looks like there isn't a hitTester param and the dispatcher function signature has changed to only accept a PointerEvent. 

I'm looking into submitting a pull request for these, but didn't know if you had any suggestions, @ajinasokan.

**Comment by mjmarrazzo** [comment]
I haven't submitted a pull request quite yet, because I want to test a few other things out. What do you think of this though? Seems to work with tap functionality. 

https://github.com/mjmarrazzo/autopilot/commit/8aa6105a92dd34b41803bcb1004e558306e8f7be

**Comment by ajinasokan** [comment]
I'm working on full migration with null safety. Do you know if null safe version conflict with non null safe projects?

**Comment by mjmarrazzo** [comment]
Oh cool. I was going to start looking into that, but I think that flutter_test might not be null safety yet, though I haven't really dived into the whole null-safety stuff yet.

As far as your question, I think its fine for a non null safe project to use a null safe dependency.

**Comment by ajinasokan** [comment]
Could you send a PR with the changes you linked above? I will do null safety migration on top of it.

**Comment by ajinasokan** [comment]
I have pushed null safety changes. I tried in a sample project and it works. Do you have any setup to test these out?

**Comment by mjmarrazzo** [comment]
Sorry, it's been crazy at work lately. I have a decent sized test base for an app at work. I'll try and run some tests against it after pulling the changes and make sure everything works. I will update on here when I do, though it might be a few days.

**Comment by RahemanAli321** [comment]
I am interested in open source contribution so do you any community that helps me for my progress? I hope you will help me

**Comment by mjmarrazzo** [comment]
@ajinasokan Sorry it took me so long to get back, but it looks like everything is working so far.

**Comment by ajinasokan** [comment]
No worries 👍
